<?php include 'view/layout/header.php';?>

<section class="content">
	<div class="container">
		<article class="post">
	        <h1>Responsive Fixed/Anchored Full Width Header and Footer</h1>
	        <p>Here is another updated version of my method to create a full wclassth header and footer, that contains centered content!</p>
	        
	        <p>'May it please your Majesty,' saclass Two, in a very humble tone, going  down on one knee as he spoke, 'we were trying'</p>
	    
	        <p>'I see!' saclass the Queen, who had meanwhile been examining the roses.  'Off with their heads!' and the procession moved on, three of the  soldiers remaining behind to execute the unfortunate gardeners, who ran  to Alice for protection.</p>
	            
	        <p>'You shan't be beheaded!' saclass Alice, and she put them into a large  flower-pot that stood near. The three soldiers wandered about for a  minute or two, looking for them, and then quietly marched off after the  others.</p>
        </article>
    </div>
</section>

<?php include 'view/layout/footer.php';?>